version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '>= 15.a'
      - dependency-name: '@types/node-fetch'
        versions:
          - '>= 3.a'
      - dependency-name: 'node-fetch'
        versions:
          - '>= 3.a'
