name: wa-update

on:
  schedule:
    - cron: '* * * * *'

jobs:
  wa-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Check Updates
        id: update
        run: npm run wa-update
        env:
          WA_COMMIT: true

      - name: Output 1
        if: ${{ steps.update.outputs.hasNewVersion == 'true' }}
        run: echo ${{ steps.update.outputs.hasNewVersion }}

      - name: Output 2
        run: echo ${{ steps.update.outputs.version }}

      - name: Output 3
        run: echo ${{ steps.update.outputs.outdated }}

      - name: LOG
        run: git log -n 10

      - name: PUSH
        run: git push
